name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (needed for Netlify CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v3
        with:
          args: deploy --dir=./ --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
